# .github/workflows/release-notification-to-jenkins.yml
name: Notify Jenkins on Release Published

on:
  release:
    types: [published]

jobs:
  notify-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Notify Jenkins
      run: |
        curl -X POST \
          -u admin:D1iXi9xlaDFK86hJ6hlVyG \
          --data token=123456 \
          https://xn--fiq06j.xn--fiqurg83j.xn--fiqs8s/jenkins/job/test-k/?token=123456
